services:
  postgres:
    image: 'postgres:latest'
    container_name: resumise-backend-postgres-dev
    environment:
      - 'POSTGRES_DB=resumise-db'
      - 'POSTGRES_PASSWORD=resumise-password'
      - 'POSTGRES_USER=resumise-user'
    ports:
      - '5433:5432'
