spring.application.name=resumise-backend

# Database connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/resumise_db
spring.datasource.username=resumise_user
spring.datasource.password=resumise_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Show SQL queries in the console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
